### ISSUE TITLE
Can't import any rdc file

### ISSUE THREAD

**Issue by leotropicae** [eliemichel/MapsModelsImporter#158]
- The .rdc file (all provided as samples)
 - Geforce gtx 1660
 - Version of this add-on = v0.3.6
 - Version of RenderDoc = 1.10 
 - Version of Blender = 2.92.0

**I'm getting the following error all the time:**

Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading. 
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

**Comment by leotropicae** [comment]
**that's the full console log**

google_maps_rd failed and returned:
Loading capture from C:\Users\PICHAU\Desktop\MapsModelsImporter-samples-master\samples\Pumpa.rdc...
Trying scraping strategy #4...
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
(Skipping drawcall ClearRenderTargetView(0.000000, 0.000000, 0.000000, 1.000000))
(Skipping drawcall ClearDepthStencilView(D=1.000000, S=00))
(Skipping drawcall Draw(4))
(Skipping drawcall Draw(4))
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 1.000000)
Not relevant yet: ClearDepthStencilView(D=1.000000, S=00)
Not relevant yet: DrawIndexed(4198)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: ClearDepthStencilView(S=00)
Not relevant yet: DrawIndexed(86)
Not relevant yet: ClearDepthStencilView(D=1.000000, S=00)
Not relevant yet: Draw(6)
Not relevant yet: Draw(210)
Not relevant yet: Draw(276)
Not relevant yet: Draw(276)
Not relevant yet: Draw(6)
Not relevant yet: Draw(144)
Not relevant yet: Draw(144)
Not relevant yet: Draw(144)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(54)
Not relevant yet: Draw(4)
Not relevant yet: CopyResource(ResourceId::93671, ResourceId::93670)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(156)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(96)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(12)
Not relevant yet: Draw(4)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(132)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(18)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(132)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(30)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(54)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(54)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(18)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(114)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 0.000000)
Not relevant yet: Draw(4)
Not relevant yet: DrawIndexed(24)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Present(ResourceId::92970)
Traceback (most recent call last):
  File "C:\Users\PICHAU\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 299, in <module>
    main(controller)
  File "C:\Users\PICHAU\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 291, in main
    scraper.run()
  File "C:\Users\PICHAU\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 217, in run
    relevant_drawcalls, capture_type = self.extractRelevantCalls(drawcalls)
  File "C:\Users\PICHAU\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 198, in extractRelevantCalls
    return self.extractRelevantCalls(drawcalls, _strategy=_strategy+1)
  File "C:\Users\PICHAU\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 166, in extractRelevantCalls
    if self.hasUniform(skipped_drawcalls[0], "_uMeshToWorldMatrix"):
IndexError: list index out of range


Extra info:
 - python = C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\bin\python.EXE
 - python_home = C:\Program Files\Blender Foundation\Blender 2.92\2.92\python
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

**Comment by Naimas** [comment]
I am having the same issue , any solution?

**Comment by eliemichel** [comment]
I've released the last version too quickly my bad, it should now be fixed (at the same version number [v0.3.6](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.6))

**Comment by Naimas** [comment]
I tried the newest release the b version but its still not working , error Importing RDC file .

**Comment by eliemichel** [comment]
@Naimas share your RDC file please otherwise I cannot test.
