### ISSUE TITLE
Incorrectly scaled building blocks at import

### ISSUE THREAD

**Issue by T0biasCZe** [eliemichel/MapsModelsImporter#256]
When importing .rdc file with capture from mapy.cz and microsoft edge, the building meshes are imported too small and dont connect correctly
![obrazek](https://user-images.githubusercontent.com/44525446/216834444-4bb7ac64-4b93-413d-9b1a-fc71f48e5e4d.png)

 - The .rdc file: https://1drv.ms/u/s!AvicUox04Y9Vjkk28x6fpsnS88qY
 - RTX 3060 (Asus Dual GeForce RTX 3060 OC Edition 12GB)
 - MMI 0.6.0
 - Renderdoc 1.25
 - Blender 3.4

**Comment by eliemichel** [comment]
Fixed by 49af880 and available in v0.6.2 (although there is still a global rotation applied to the capture that idk how to fix).

**Comment by T0biasCZe** [comment]
tried it, and the issue remains... 
![obrazek](https://user-images.githubusercontent.com/44525446/218328197-9596ad13-d800-4cc3-a5aa-209b6101a0cd.png)
i also tried enabling textures and scaling it up manually, and it looks like it imports each mesh 4 times based on the textures (though idk if its issue with MMI, or with renderdoc)
![obrazek](https://user-images.githubusercontent.com/44525446/218328264-a0ce2517-46ae-4a29-85e3-a39ff40cd1a6.png)

**Comment by eliemichel** [comment]
both of these problem should have been fixed with v0.6.2 could you try uninstalling and reinstalling? I'm gonna double check on my end as well
